spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jinyou_travel
    username: root
    password: 123456789
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 驼峰转换
  type-handlers-package: org.apache.ibatis.type

aliyun:
  oss:
    accessKeyId: 
    accessKeySecret:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: jinyou-travel
    region: cn-beijing

wx:
  pay:
    appId: 你的小程序APPID
    mchId: 你的商户号
    mchKey: 你的商户密钥
    notifyUrl: https://你的域名/api/order/wxNotify