spring :
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jinyou_travel
    username: root
    password: 123456789
server:
  port: 8081
mybatis:
    configuration:
        map-underscore-to-camel-case : true # 开启驼峰命名和下划线命名的自动转换